### ISSUE TITLE
Use proxies?

### ISSUE THREAD

**Issue by ghost** [CezarLuiz0/rest-mapper#1]
Some rest-services have too much rest points. What if we use proxies instead of pre-defining object methods.
Concept example: 

```
let Github = new Mapper({
  host: 'https://api.github.com',
  proxies: true,
  // maybe_some_additional_logic
  //...
  }
});
Github.Users.get() // proxied to GET https://api.github.com/users
Github.Users.defunct.get() // proxied to GET https://api.github.com/users/defunct
```

About proxies: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy
I use proxy before in this repo: https://github.com/allprime/mobizon-node

**Comment by cezarsmpio** [comment]
Hi @nurzhanpy, sorry!!!!!

`rest-mapper` was built using `axios` as AJAX core. So, you can use its all configs. [Please, take a look on `axios` proxy configs](https://github.com/mzabriskie/axios#request-config).

Updating your example, you can use for ALL requests:

``` javascript
let Github = new Mapper({
  host: 'https://api.github.com',
  defaults: {
    proxy: {
      host: '127.0.0.1',
      port: '8888'
    }
  }
});
```

Or you can set proxy for specific request, something like this:

``` javascript
let Github = new Mapper({
  host: 'https://api.github.com',

  resources: {
    Users: {
      get: {
        url: '/users',
        proxy: {
          host: '172.34.21.187',
          port: '3300'
        }
      }
    }
  }
});
```

I hope helped you!

**Comment by ghost** [comment]
Hi @cezarlz 
You don't understand. I don't mean web proxies. I mean javascript Proxy object.
Imagine situation when you define mapper, and every time when github add a new api point you need add it in Mapper definition, what if mapper build requests url from mapper methods name on demand. Please, read about Proxy object on MDN:  https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by Robinfr** [comment]
Proxy objects cannot be transpiled by Babel and not all browsers support it.. This would for example completely remove support for IE..
